version: '3.8'

services:
    nginx:
        image: nginx:1.23-alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm-server

    php-fpm-server:
        build:
            context: ./server
            dockerfile: docker/php-fpm-server/Dockerfile
        volumes:
            - ./server:/var/www/html:cached
        depends_on:
            - db

     # let's decide if we will use the same Dockerfile for both client and server
#    php-fpm-client:
#        build:
#            context: ./client
#            dockerfile: ../docker/php-fpm/Dockerfile
#        volumes:
#            - ./client:/var/www/client:cached

    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ecoideabooster
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: alex
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"

volumes:
    db_data:
